const request = require("request");
const fs = require("fs")
const axios = require("axios")
module.exports.config = {
  name: "hentaiz",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Thanh Dz (fix lại by CHIP)",
  description: "Ảnh Hentaiz",
  commandCategory: "Nsfw",
  usages: "hentaiz",
  cooldowns: 5,
  dependencies: {
    "request": "",
    "fs": "",
    "axios": ""
  }
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
	var link = [
"https://i.imgur.com/mNesqCm.jpg",
"https://i.imgur.com/ChtMmje.jpg",
"https://i.imgur.com/2oTwWjZ.png",
"https://i.imgur.com/ZOcTTvR.jpg",
"https://i.imgur.com/ccLl6Ym.png",
"https://i.imgur.com/bdQ5fK9.png",
"https://i.imgur.com/zyqGxHc.png",
"https://i.imgur.com/1dFL3ZI.png",
"https://i.imgur.com/SKsfMCE.jpg",
"https://i.imgur.com/vhinUxm.png",
"https://i.imgur.com/5QXTkQr.jpg",
"https://i.imgur.com/cMeEbZe.jpg",
"https://i.imgur.com/HRDcYSW.jpg",
"https://i.imgur.com/sp1SnE4.jpg",
"https://i.imgur.com/Ki3hy27.jpg",
"https://i.imgur.com/8bxgU0f.jpg",
"https://i.imgur.com/7iDnRg6.jpg",
"https://i.imgur.com/shKYOem.png",
"https://i.imgur.com/MGNxYj4.jpg",
"https://i.imgur.com/1DTrdAl.jpg",
"https://i.imgur.com/xAKKpfT.png",
"https://i.imgur.com/ChtMmje.jpg",
"https://i.imgur.com/ujo6Yvu.jpg",
"https://i.imgur.com/dVcSVDs.jpg",
"https://i.imgur.com/rpdXJEa.jpg",
"https://i.imgur.com/sToM2cj.png",
"https://i.imgur.com/wzUFRb9.png",
"https://i.imgur.com/n378ZMT.png",
"https://i.imgur.com/A8dKVOY.jpg",
"https://i.imgur.com/6a7lQUa.jpg",
"https://i.imgur.com/Oc1XLXW.jpg",
"https://i.imgur.com/MpQ7qN3.png",
"https://i.imgur.com/GK2iXnb.jpg",
"https://i.imgur.com/cwHOc0j.jpg",
"https://i.imgur.com/NHRGsp6.jpg",
"https://i.imgur.com/Ia9ugv3.jpg",
"https://i.imgur.com/CqszBU7.jpg",
"https://i.imgur.com/JHm5muL.jpg",
"https://i.imgur.com/509DTo9.png",
"https://i.imgur.com/JjvzvuI.jpg",
"https://i.imgur.com/hMljgoy.jpg",
"https://i.imgur.com/lOn0Vru.jpg",
"https://i.imgur.com/eDFtiW3.jpg",
"https://i.imgur.com/JYKT9Uv.jpg",
"https://i.imgur.com/pG0YTtt.jpg",
"https://i.imgur.com/tZP3MMz.png",
"https://i.imgur.com/RM9ukif.jpg",
"https://i.imgur.com/gMRKKyj.png",
"https://i.imgur.com/m4WWhGW.png",
"https://i.imgur.com/3XcAUud.jpg",
"https://i.imgur.com/ycnn0HV.png",
"https://i.imgur.com/8VjmAbA.jpg",
"https://i.imgur.com/vXgbs3j.jpg",
"https://i.imgur.com/OQ3d05j.jpg",
"https://i.imgur.com/bXGDK0Y.jpg",
"https://i.imgur.com/UcvGgH7.jpg",
"https://i.imgur.com/Ei4JcHB.jpg",
"https://i.imgur.com/jHcd7na.jpg",
"https://i.imgur.com/FaN7cnv.png",
"https://i.imgur.com/hH0of56.png",
"https://i.imgur.com/pmUdyLW.jpg",
"https://i.imgur.com/gpsqjlX.jpg",
"https://i.imgur.com/ohpsz0U.jpg",
"https://i.imgur.com/Ar8ioUD.png",
"https://i.imgur.com/WsVWcq2.jpg",
"https://i.imgur.com/XzQTER5.jpg",
"https://i.imgur.com/0t1yKln.jpg",
"https://i.imgur.com/iXAHEqa.jpg",
"https://i.imgur.com/7yAtWmQ.png",
"https://i.imgur.com/71f21Ix.png",
"https://i.imgur.com/x0bcEFl.png",
"https://i.imgur.com/lH7lYVc.png",
"https://i.imgur.com/ba8LkRB.png",
"https://i.imgur.com/FsP5lSm.jpg",
"https://i.imgur.com/X25um8b.jpg",
"https://i.imgur.com/rSBexdO.png",
"https://i.imgur.com/tTTXPgb.png",
"https://i.imgur.com/MaBiBiD.png",
"https://i.imgur.com/cZwQjP7.jpg",
"https://i.imgur.com/iCFsBHc.jpg",
"https://i.imgur.com/dTZGPiM.jpg",
"https://i.imgur.com/bQ5xRTG.png",
"https://i.imgur.com/aFXDHWL.jpg",
"https://i.imgur.com/tdU2fbU.png",
"https://i.imgur.com/faRtrw6.png",
"https://i.imgur.com/id08VTo.png",
"https://i.imgur.com/heLM5yF.png",
"https://i.imgur.com/qwRAAlu.png",
"https://i.imgur.com/7lR2uR3.png",
"https://i.imgur.com/vL15U0T.jpg",
"https://i.imgur.com/jhuTb7V.png",
"https://i.imgur.com/drfQ40t.png",
"https://i.imgur.com/uUBPHaJ.png",
"https://i.imgur.com/RG3okEu.jpg",
"https://i.imgur.com/Z0TXFH4.jpg",
"https://i.imgur.com/3m8hzJN.jpg",
"https://i.imgur.com/RhID5od.png",
"https://i.imgur.com/ya7YRI0.jpg",
"https://i.imgur.com/LD3RVrr.jpg",
"https://i.imgur.com/1w2rB4L.png",
"https://i.imgur.com/EQL8NaV.jpg",
"https://i.imgur.com/znt95h8.jpg",
"https://i.imgur.com/nygmcPC.png",
"https://i.imgur.com/HqD91sB.png",
"https://i.imgur.com/5Dr78D4.jpg",
"https://i.imgur.com/DdOnuos.png",
"https://i.imgur.com/3E5zzCr.png",
"https://i.imgur.com/CTzsGiL.png",
"https://i.imgur.com/awlG1W2.jpg",
"https://i.imgur.com/sAbp1dU.jpg",
"https://i.imgur.com/GSSJLSF.png",
"https://i.imgur.com/vDM906Y.jpg",
"https://i.imgur.com/hCoFifQ.jpg",
  ];
    var max = Math.floor(Math.random() * 6);  
var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 1000) api.sendMessage("Bạn cần 1000 đô để xem ảnh ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 1000})
   var callback = () => api.sendMessage({body:`Ảnh Hentaiz\nSố Ảnh: ${link.length}\n-1000 đô !`,attachment: fs.createReadStream(__dirname + "/cache/28.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/28.jpg"), event.messageID); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)] + (max - min))).pipe(fs.createWriteStream(__dirname+"/cache/28.jpg")).on("close",() => callback());
     }
   };
